[build]
  # Build command
  command = "cd frontend && yarn build"
  
  # Directory to publish (relative to root of your repo)
  publish = "frontend/build"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # Yarn version
  YARN_VERSION = "1.22.22"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://us.i.posthog.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://us.i.posthog.com"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Page-specific redirects for SEO
[[redirects]]
  from = "/bmi-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301