[build]
  # Build command - use frozen lockfile for consistent builds
  command = "cd frontend && yarn install --frozen-lockfile && yarn build"
  
  # Directory to publish (relative to root of your repo)
  publish = "frontend/build"

# Netlify Prerender Plugin - Solves SEO & Crawler Issues
[[plugins]]
  package = "netlify-plugin-prerender"
  
  [plugins.inputs]
    # Routes to prerender for SEO (crawlers will see full HTML)
    routes = [
      "/",
      "/body-fat-calculator",
      "/army-body-fat-calculator", 
      "/lean-body-mass-calculator",
      "/ideal-weight-calculator",
      "/healthy-weight-calculator",
      "/body-type-calculator",
      "/body-surface-area-calculator",
      "/carbohydrate-calculator",
      "/protein-calculator",
      "/fat-intake-calculator",
      "/calorie-calculator",
      "/tdee-calculator",
      "/bmr-calculator",
      "/macro-calculator",
      "/pace-calculator",
      "/calories-burned-calculator",
      "/one-rep-max-calculator",
      "/target-heart-rate-calculator",
      "/pregnancy-calculator",
      "/pregnancy-weight-gain-calculator",
      "/due-date-calculator",
      "/ovulation-calculator",
      "/conception-calculator",
      "/period-calculator",
      "/gfr-calculator",
      "/bac-calculator",
      "/privacy-policy",
      "/terms-conditions",
      "/contact-us"
    ]
    
    # Rendering options
    concurrency = 4
    renderAfterTime = 1000
    renderAfterDocumentEvent = "custom-render-trigger"

[build.environment]
  # Node version - Updated to 20 for react-router-dom@7.9.1 compatibility
  NODE_VERSION = "20"
  
  # Yarn version
  YARN_VERSION = "1.22.22"

# SPA routing configuration - MOST IMPORTANT FOR FIXING 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Ensure specific calculator routes work
[[redirects]]
  from = "/body-fat-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/army-body-fat-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/lean-body-mass-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ideal-weight-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/healthy-weight-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/body-type-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/body-surface-area-calculator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/terms-conditions"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://us.i.posthog.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://us.i.posthog.com"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Page-specific redirects for SEO
[[redirects]]
  from = "/bmi-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301