[build]
  publish = "frontend/build"
  command = "cd frontend && yarn install --force && yarn build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

# Redirect rules for SEO and URL structure
[[redirects]]
  from = "/bmi-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/body-mass-index-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/calculate-bmi"
  to = "/"
  status = 301

[[redirects]]
  from = "/bmi"
  to = "/"
  status = 301

[[redirects]]
  from = "/bodyfat"
  to = "/body-fat"
  status = 301

[[redirects]]
  from = "/bodyfat-calculator"
  to = "/body-fat"
  status = 301

[[redirects]]
  from = "/calorie-calculator"
  to = "/calories"
  status = 301

[[redirects]]
  from = "/tdee-calculator"
  to = "/calories"
  status = 301

[[redirects]]
  from = "/bmr-calculator" 
  to = "/calories"
  status = 301

[[redirects]]
  from = "/macro-calculator"
  to = "/macros"
  status = 301

[[redirects]]
  from = "/macronutrient-calculator"
  to = "/macros"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Preload critical resources
[[headers]]
  for = "/"
  [headers.values]
    Link = '''</static/css/main.css>; rel=preload; as=style,
              </static/js/main.js>; rel=preload; as=script'''